name: repo-sunsetter
description: "A GitHub Action to prepare a repository for archival"

inputs:
  GITHUB_TOKEN:
    description: "GitHub token for authentication and creating issues & PRs"
    required: true

  METADATA_FILE_TYPE:
    description: "Metadata file in the repository (e.g. code.json, codemeta, publiccode.yml)"
    required: false
    default: "code.json"
  
  USE_MATURITY_MODEL_TIERS:
    description: "Flag to determine if maturity model tiers should be used for issue generation"
    required: true
    default: "false"
  
  CHECKLIST_LINK:
    description: "A link to the archival checklist to be included in the issue body. The checklist must be in the form of a .md file. The link must serve the file as a static raw text file (i.e. uses raw.githubusercontent.com). Only used if USE_MATURITY_MODEL_TIERS is false"
    required: false
    default: "https://raw.githubusercontent.com/DSACMS/repo-sunsetter/main/checklists/TEMPLATE_ARCHIVAL_CHECKLIST.md"

  ARCHIVE_NOTICE_TEXT:
    description: "Custom text to include in the archival notice (optional)"
    required: false

runs:
  using: "composite"
  steps:
    
    - name: Create archival checklist issue
      id: create-issue
      uses: DSACMS/repo-sunsetter/actions/create-issue@DSACMS/nat/gen-action
      with:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        USE_MATURITY_MODEL_TIERS: ${{ inputs.USE_MATURITY_MODEL_TIERS }}
        CHECKLIST_LINK: ${{ inputs.CHECKLIST_LINK }}
    
    - name: Update code.json using archival mode
      if: ${{ inputs.METADATA_FILE_TYPE == 'code.json' }}
      uses: DSACMS/automated-codejson-generator@main
      with:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        BRANCH: "main"
        SKIP_PR: "false"
        ARCHIVE: "true"
    
    - name: Update README.md with archival notice
      id: update-readme
      uses: DSACMS/repo-sunsetter/actions/update-readme@DSACMS/nat/gen-action
      with:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        ARCHIVE_NOTICE_TEXT: ${{ inputs.ARCHIVE_NOTICE_TEXT }}
